### ISSUE TITLE
Add C++14 grammar

### ISSUE THREAD

**Issue by asmatic77** [Munkei/atom-linter-cppcheck#1]
Hello!
I was just developing my own cppcheck linter when I say your own... I'm not used to github way of proposing changes and It seems that currently my atom setup is confused between your plugin and my plugin.

But I just wanted to add grammar support to your package. Its just adding a new case statement. I guess that that issue can happen if the user has installed the language-cpp14 plugin for atom.

const grammar = textEditor.getGrammar().name;
      switch (grammar) {
        case 'C':
          args.push('--language=c');
          break;

```
    case 'C++':
case 'C++14':
      args.push('--language=c++');
      break;

    default:
      console.warn(
        `[linter-cppcheck] Unrecognised grammar ‘${grammar}’`
      );
      break;
  }
```

Thanks

**Comment by biffen** [comment]
I wasn't even aware of that package's existence (so thanks for the tip!), but it seems like a small enough fix. Should be out soon.

**Comment by biffen** [comment]
FYI, I'll make a release with the fix when I have the time, which might not be until next week. In the meantime you can clone/download `HEAD`.
