### ISSUE TITLE
Migrate to Linter v2

### ISSUE THREAD

**Issue by biffen** [Munkei/atom-linter-cppcheck#13]
Linter v2 is out, with a new API. Linter Cppcheck should start using it.

See [Linter Documentation § Migration Guides](https://github.com/steelbrain/linter/tree/master/docs#migration-guides).

**Comment by Arcanemagus** [comment]
You'll likely want to also look into adding [`atom-package-deps@^4.5.0`](https://github.com/steelbrain/package-deps/) so you can be sure your users have Linter v2 installed.
