### ISSUE TITLE
CppCheck Showing Error

### ISSUE THREAD

**Issue by sid00786** [Munkei/atom-linter-cppcheck#14]
Whenever i compile a c++ programme in atom, an error pops up -;

[linter] Error Running cppcheck.
See developer console for more info.

**Comment by biffen** [comment]
Have you installed Cppcheck and [configured](https://github.com/Munkei/atom-linter-cppcheck#configuration) its location and/or made sure it's on the `$PATH`?

If the above does not work, could you show us the Cppcheck-related messages in the developer console, if any, as well as your configuration?

Which operating system are you using?

**Comment by biffen** [comment]
I'll close this now, since it's been a while without a reply. Feel free to reopen if there's any more information.
