### ISSUE TITLE
Clear instructions how to even get this thing started for beginners?

### ISSUE THREAD

**Issue by Error808** [Munkei/atom-linter-cppcheck#17]
I installed linter and installed cppcheck and I have no clue how to even get this started, it doesn't check my errors.
I just want to something to live error check my code such as syntax error and etc instead of me using make file to find my errors. that's it.
I don't understand why there are no clear instructions on what to do after you installed these packages.

**Comment by biffen** [comment]
It’s been years since I last used this myself, but as I recall there’s no live linting, only on save.

What kind of instructions would you like to see, that aren’t in the README?

**Comment by Error808** [comment]
Thanks foe the reply.
I am using mac Mojave and it just doesn’t work.
Even when I save the file( with or without autosave plugin ), doesn’t work.

On Feb 24, 2019, at 10:29 PM, Theo Willows <notifications@github.com> wrote:

It’s been years since I last used this myself, but as I recall there’s no live linting, only on save.

What kind of instructions would you like to see, that aren’t in the README?

**Comment by biffen** [comment]
First of all; I’ve never tried this on MacOS, so I can’t say that it _should_ work. But then agian, I’ve never had any reports that it doesn’t, so who knows.

Without more to go on, I can only give a few general pointers:

- Have you got `cppcheck` in your `$PATH`? I.e. does `cppcheck --version` (verbatim) work in a terminal?

- Or have you configured the path to the `cppcheck` executable in Linter Cppcheck’s settings?

Also note that this software is no longer maintained. I’ll do my best to respond to this issue, but after that this whole repository will be archived. I will not make any changes to the code and no new releases.

**Comment by Error808** [comment]
cppcheck command doesn’t work in the terminal, so i assume i don’t have it.
how do I configure the path to the cppcheck ?

**Comment by Error808** [comment]
I have installed cppcheck, but it is not in the path directory. how do I check if it is in the path directory

**Comment by biffen** [comment]
See [this](https://apple.stackexchange.com/questions/41542/adding-a-new-executable-to-the-path-environment-variable).

But note that you don’t have to do that if you configure Linter Cppcheck with the full path to `cppcheck` (see the README).

**Comment by Error808** [comment]
I read the README, but it doesn’t say how to configure linter CPPcheck with the full path to cppcheck for mac.
I have cppcheck here, what do I do next ?

**Comment by Error808** [comment]
Is this where you referring to ? (README)

**Comment by Error808** [comment]
is this correct way?
still doesnt work

**Comment by Error808** [comment]
Hello
I have tried everything with my best knowledge and still doesnt work.
I was able to understand what executable means and I gave it the full path for cppcheck.
I already installed linter plug in.
What else can I do?

**Comment by biffen** [comment]
This is the relevant part of the README:

> ## Configuration
>
> The package settings are available at: _Edit_ > _Preferences_ > _Packages_ > _linter-cppcheck_
>
> You can configure the location of the Cppcheck executable. The default is to look for `cppcheck` in your `$PATH` environment variable. In most cases this should ‘just work’.

Could you show me the _exact_ configuration you’re using, the path to the `cppcheck` executable and how you determine it doesn’t work?

**Comment by Error808** [comment]
Yes i have read that.
But my cppcheck doesn’t work.

On Feb 25, 2019, at 2:00 AM, Theo Willows <notifications@github.com> wrote:

This is the relevant part of the README:

Configuration

The package settings are available at: Edit > Preferences > Packages > linter-cppcheck

You can configure the location of the Cppcheck executable. The default is to look for cppcheck in your $PATH environment variable. In most cases this should ‘just work’.

Could you show me the exact configuration you’re using, the path to the cppcheck executable and how you determine it doesn’t work?

**Comment by biffen** [comment]
I'd like to help, but there's really nothing I can do without more information.

**Comment by Error808** [comment]
What else do you need to know?
I can provide you

On Feb 25, 2019, at 10:48 AM, Theo Willows <notifications@github.com> wrote:

I'd like to help, but there's really nothing I can do without more information.

**Comment by biffen** [comment]
> Could you show me the _exact_ configuration you’re using, the path to the `cppcheck` executable and how you determine it doesn’t work?

And while we're at it, can you confirm that `cppcheck` works on its own, e.g. in a terminal?

**Comment by Error808** [comment]
Were you able to find out?

**Comment by biffen** [comment]
Was I able to find out _what_?!

I'm waiting for _you_ to supply further information.

**Comment by Error808** [comment]
I sent you two pictures, did you receive them?

**Comment by biffen** [comment]
No, I didn't.

I don't think GitHub likes pictures sent over email. You'd better use the website.

**Comment by Error808** [comment]
please email me at Kamsignal21@gmail.com
I will send u screen shots of where my cppcheck file is and configuration on atom.

**Comment by biffen** [comment]
I'm sorry, I can't do that. Post the pictures here on GitHub.

**Comment by Error808** [comment]
![screen shot 2019-02-25 at 11 32 10 am](https://user-images.githubusercontent.com/40338143/53470755-6a160e80-3a17-11e9-9535-87e21ecdd10e.png)
![screen shot 2019-02-25 at 11 36 24 am](https://user-images.githubusercontent.com/40338143/53470761-6f735900-3a17-11e9-91e6-f41fc7cfe14a.png)

**Comment by Error808** [comment]
didn't know i could post

**Comment by Error808** [comment]
second picture is the location of the cppcheck
and first picture is the proof that cppcheck by it self works

**Comment by biffen** [comment]
At a glance it looks right.

How do you test it?

**Comment by Error808** [comment]
first picture shows that i checked with a  main.cpp ( with errors )

**Comment by Error808** [comment]
cppcheck main.cpp

**Comment by biffen** [comment]
No, I mean how do you test Linter Cppcheck?

**Comment by Error808** [comment]
![screen shot 2019-02-26 at 10 51 21 pm](https://user-images.githubusercontent.com/40338143/53471310-0a206780-3a19-11e9-94f6-d92017c4ceee.png)

**Comment by Error808** [comment]
it doesn't show anything

**Comment by Error808** [comment]
![screen shot 2019-02-26 at 10 54 21 pm](https://user-images.githubusercontent.com/40338143/53471442-77cc9380-3a19-11e9-9d3e-60cdfee90f04.png)
![screen shot 2019-02-26 at 10 54 44 pm](https://user-images.githubusercontent.com/40338143/53471461-84e98280-3a19-11e9-9d50-6a5d073fdbfa.png)

**Comment by Error808** [comment]
just for reference^

**Comment by biffen** [comment]
1. I don't know whether Cppcheck can produce any warnings if there are such syntactical errors.

2. Did you save the file?

3. Could you check Atom's console for messages?

**Comment by Error808** [comment]
1) what can cppcheck then?
2) yes
3) how?

**Comment by biffen** [comment]
https://discuss.atom.io/t/how-to-view-console-window-debugger/10098

**Comment by Error808** [comment]
what do i do with atoms console?
how does it work

**Comment by biffen** [comment]
You know what? That's it. I can't guide you through every little thing. This software is not maintained any more. If if doesn't work and you haven't got the skills to solve it, then tough luck.

Good luck working this out on your own. I'll close this now.
