### ISSUE TITLE
Option to configure the execution time and show if linter is running

### ISSUE THREAD

**Issue by Costallat** [Munkei/atom-linter-cppcheck#2]
Hello, I don't know if this is possible, but would be nice if I could configure the execution timeout, because sometimes with a big file, the "linter" never finish, because execution is stopped in the middle.

Other problem is that I can't know when "linter" is running or not, it would be nice show somewhere that "linter" is running, so I can know when it finished! Today I have to save the file and wait looking to the screen to see if something happens!

**Comment by biffen** [comment]
Both good ideas. Maybe the libraries used ([Linter](https://atom.io/packages/linter) and [atom-linter](https://www.npmjs.com/package/atom-linter)) have functionality for all or parts of it.

However, I'm afraid I will not be able to look into this any time soon (travel, personal reasons). (Something like 1–2 months.)

**Pull requests are welcome**, but I won't be able to merge them or make releases in the near future either.
