### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by Natipare** [Munkei/atom-linter-cppcheck#5]
It is just not. I have windows 10, have installed cppcheck, and i still does not work

**Comment by Natipare** [comment]
here you have a sc with basic program
![bez tytulu](https://cloud.githubusercontent.com/assets/24441552/21024157/bff57eac-bd83-11e6-848b-a2ddf66c9151.png)

**Comment by biffen** [comment]
Have you configured the path to the Cppcheck executable (*Settings* > *Packages* > *Linter Cppcheck* > *Executable*)? If you have, what's the value? And, while we're at it; what are the rest of the settings?

**Comment by Natipare** [comment]
I did not, it says "Default:cppcheck" and when i click on it changes to only "cppcheck"

**Comment by biffen** [comment]
You have to configure the path to the Cppcheck executable. (I haven't got access to a Windows system at the moment, but the path would be something like `C:\Program Files\Cppcheck\bin\cppcheck.exe`, but you'll have to look it up yourself, I'm afraid.)

I'll close this issue now. If things still don't work after you've configured the path feel free to open a new issue.
