### ISSUE TITLE
Its still not working (Part 2)

### ISSUE THREAD

**Issue by Natipare** [Munkei/atom-linter-cppcheck#6]
Okay everything is on the sc i believe

![bez tytulu](https://cloud.githubusercontent.com/assets/24441552/21064725/bae09a1c-be5c-11e6-9b2e-0921ea6f2629.png)

**Comment by Natipare** [comment]
Quick summary: there was no "bin" folder and cppcheck.exe was directly in the "cppcheck" folder.
There is a new error (or not new, i dont recall seeing it but who knows). You can't see it on the sc but it still shows "no issues" on the bottom.

**Comment by Natipare** [comment]
Thats how the inside of cppcheck looks like

![bez tytulu](https://cloud.githubusercontent.com/assets/24441552/21073560/25d2fec0-bee2-11e6-85ab-5194eab287af.png)

**Comment by biffen** [comment]
You configured it with the wrong path:

`C:\Program Files\cppcheck.exe` → `C:\Program Files\Cppcheck\cppcheck.exe`
