### ISSUE TITLE
Deprecated selector in `linter-cppcheck/styles/linter-cppcheck.less`

### ISSUE THREAD

**Issue by quarthex** [Munkei/atom-linter-cppcheck#8]
In `linter-cppcheck/styles/linter-cppcheck.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-highlight.information:not(.line-number),
.linter-highlight.information:not(.line-number)` => `atom-text-editor.editor .linter-highlight.information:not(.line-number),
.linter-highlight.information:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.information .linter-gutter,
.linter-highlight.information .linter-gutter` => `atom-text-editor.editor .linter-highlight.information .linter-gutter,
.linter-highlight.information .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.information .region,
.linter-highlight.information .region` => `atom-text-editor.editor .linter-highlight.information .region,
.linter-highlight.information .region`

* `atom-text-editor::shadow .linter-highlight.performance:not(.line-number),
.linter-highlight.performance:not(.line-number),
atom-text-editor::shadow .linter-highlight.portability:not(.line-number),
.linter-highlight.portability:not(.line-number),
atom-text-editor::shadow .linter-highlight.style:not(.line-number),
.linter-highlight.style:not(.line-number)` => `atom-text-editor.editor .linter-highlight.performance:not(.line-number),
.linter-highlight.performance:not(.line-number),
atom-text-editor.editor .linter-highlight.portability:not(.line-number),
.linter-highlight.portability:not(.line-number),
atom-text-editor.editor .linter-highlight.syntax--style:not(.line-number),
.linter-highlight.style:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.performance .linter-gutter,
.linter-highlight.performance .linter-gutter,
atom-text-editor::shadow .linter-highlight.portability .linter-gutter,
.linter-highlight.portability .linter-gutter,
atom-text-editor::shadow .linter-highlight.style .linter-gutter,
.linter-highlight.style .linter-gutter` => `atom-text-editor.editor .linter-highlight.performance .linter-gutter,
.linter-highlight.performance .linter-gutter,
atom-text-editor.editor .linter-highlight.portability .linter-gutter,
.linter-highlight.portability .linter-gutter,
atom-text-editor.editor .linter-highlight.syntax--style .linter-gutter,
.linter-highlight.style .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.performance .region,
.linter-highlight.performance .region,
atom-text-editor::shadow .linter-highlight.portability .region,
.linter-highlight.portability .region,
atom-text-editor::shadow .linter-highlight.style .region,
.linter-highlight.style .region` => `atom-text-editor.editor .linter-highlight.performance .region,
.linter-highlight.performance .region,
atom-text-editor.editor .linter-highlight.portability .region,
.linter-highlight.portability .region,
atom-text-editor.editor .linter-highlight.syntax--style .region,
.linter-highlight.style .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Foadsf** [comment]
I also have the exact same issue after I updated atom on my mac a couple of days ago. many other packages has been already updated to solve this depreciation issue, but this package is lagging behind.
