### ISSUE TITLE
False positives: "struct member is never used"

### ISSUE THREAD

**Issue by neumannrf** [Munkei/atom-linter-cppcheck#9]
While scanning a `*.h` file for **Style** errors, the linter flags as _"not being used"_ several members of a `struct` defined therein, even though they **are all used** inside the `*.cc` file that includes the `*.h`.

Searching the internet I got the impression that `*.h` files are **not** supposed to be scanned independently. Instead, they are scanned from within the `*.cc` when a `#include` directive is found.

Is it possible to disable scanning of C++ headers (for **Style** errors)?

**Comment by biffen** [comment]
Since Atom doesn't provide different grammars for headers and source files (as far as I can tell) I'm afraid the answer is *no*.
